### ISSUE TITLE
Support nested <kbd> elements

### ISSUE THREAD

**Issue by rbottomley** [jGleitz/markdown-it-kbd#95]
According to the spec ([HTML5 kbd spec](https://www.w3.org/TR/html52/textlevel-semantics.html#the-kbd-element)), `kbd` elements are nested to represent keycaps as in:

`<p>To make George eat an apple, press <kbd><kbd>Shift</kbd>+<kbd>F3</kbd></kbd></p>`

but this does not work:

`To make George eat an apple, press [[[[Shift]]+[[F3]]]]`

results in:

`<p>To make George eat an apple, press [<kbd>[Shift</kbd>+<kbd>F3</kbd>]]</p>`

**Comment by jGleitz** [comment]
Hi, thanks for reporting this!

When writing this plugin, I assumed that there was no meaningful reason to use nested `<kbd>` elements. I was not aware that the spec actually assigns meaning to this combination. I do not quite agree with the concept: For my head, it makes much more sense to use `<kbd>` just for the keys and some semantic-free markup like `<span>`s for key combinations.

However, I agree that this plugin should support this use case, since it is explicitly part of the specification. I hope I’ll have time to work on it soon! A PR would also be welcome, of course.
